### PR TITLE
Rebase to linkedin

### PR DESCRIPTION
**Pull request by kmulvey**
rebased to upstream, preferred linkedin when conflicts arose, fixed tests, updated deps

after this is done it will be easier to see what the differences are between this repo and linkedin. We can then document those differences or get them merged upstream so we can just use linkedin.

### CODE REVIEW

**Comment by kmulvey** [comment]
last night i developed a theory as to why github says there are conflicts after i rebased: i rebased against linkedin/master but PR'd against MediaMath/master. 

@ajaxisme @maxaf does that add up?

**Comment by ajaxisme** [comment]
It makes sense to make master consistent with the upstream. Unless there are any breaking changes that we should inform the users about.

**Comment by maxaf** [comment]
Would the following be easier to manage?
1. Branch off `MediaMath/master`. Call this branch `foo`.
1. Merge `upstream/master` into `foo`. Resolve any conflicts, thus making `foo` a combination of our local changes as well as upstream updates since the last time we've synced up with them.
1. PR from `foo` to `MediaMath/master`.

**Comment by kmulvey** [comment]
thats kinda what i did:

remotes:
origin = kmulvey
mm = mm
upstream = linkedin

- remote update
- checkout master
- reset --hard mm/master
- checkout -b rebase-to-linkedin
- rebase upstream/master
- resolve, continue, resolve, continue ....
- pr to MM/master

**Comment by maxaf** [comment]
Well, you did a rebase, not a merge, which is a rewrite of history with the goal of pretending that our commits on top of upstream's `master` branch took place just now, as opposed to when they actually did. A merge is more honest, in the sense that it resyncs our history with upstream's with the understanding that we've also made changes along the way. The upside of merging is that the diffs representing our changes will have been applied atop parent commits that they were originally written for.

**Pull request closed without merging**
